package com.kchn.blog.api.Article;

import javax.validation.constraints.NotEmpty;

/**
 * This class describes the body of the Post request used to create articles.
 * This contains all of the user specify-able fields for new articles
 * 
 * Notice that id, url, and published dates have been omitted. These will be generated by the backend application.
 * @author kevin
 *
 */
public class ArticlePostDTO {

    @NotEmpty
    private String title;
    
    private String byline;

    @NotEmpty
    private String content;
    
    private String metaTitle;
    
    private String metaDesc;
    
    @NotEmpty
    private String author;

    public ArticlePostDTO() {
        super();
    }    
    
    public ArticlePostDTO(@NotEmpty String title, String byline,
        @NotEmpty String content, String metaTitle, String metaDesc,
        @NotEmpty String author) {
        super();
        this.title = title;
        this.byline = byline;
        this.content = content;
        this.metaTitle = metaTitle;
        this.metaDesc = metaDesc;
        this.author = author;
    }


    public String getTitle() {
        return title;
    }

    public String getByline() {
        return byline;
    }

    public String getContent() {
        return content;
    }

    public String getMetaTitle() {
        return metaTitle;
    }

    public String getMetaDesc() {
        return metaDesc;
    }

    public String getAuthor() {
        return author;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setByline(String byline) {
        this.byline = byline;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }

    public void setMetaDesc(String metaDesc) {
        this.metaDesc = metaDesc;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    
    
    
}
